/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.*;
import javax.swing.JOptionPane;

/**
 *
 * @author liborio
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        cmdLimpiar.setEnabled(false);
        cmdCalcular.setEnabled(true);
        cmdFraccionarios.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPrimerEntero = new javax.swing.JTextField();
        txtNumeroUno = new javax.swing.JTextField();
        txtDenominadorUno = new javax.swing.JTextField();
        cmbOper = new javax.swing.JComboBox<>();
        txtNumeroDos = new javax.swing.JTextField();
        txtDemominadorDos = new javax.swing.JTextField();
        txtEnteroDos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNumeroTres = new javax.swing.JTextField();
        txtDenominadorTres = new javax.swing.JTextField();
        txtEnteroTres = new javax.swing.JTextField();
        cmdCalcular = new javax.swing.JButton();
        cmdLimpiar = new javax.swing.JButton();
        cmdFraccionarios = new javax.swing.JButton();
        txtNumerador1 = new javax.swing.JTextField();
        txtDemoninador = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel1.setText("Numeros Mixtos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        txtPrimerEntero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrimerEnteroKeyTyped(evt);
            }
        });
        jPanel1.add(txtPrimerEntero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 60, 30));

        txtNumeroUno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroUnoKeyTyped(evt);
            }
        });
        jPanel1.add(txtNumeroUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 60, 30));

        txtDenominadorUno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDenominadorUnoKeyTyped(evt);
            }
        });
        jPanel1.add(txtDenominadorUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 60, 30));

        cmbOper.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbOper.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Suma", "Resta", "Multiplicación", "División" }));
        jPanel1.add(cmbOper, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, 30));

        txtNumeroDos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroDosKeyTyped(evt);
            }
        });
        jPanel1.add(txtNumeroDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 60, 30));

        txtDemominadorDos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDemominadorDosKeyTyped(evt);
            }
        });
        jPanel1.add(txtDemominadorDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 60, 30));

        txtEnteroDos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEnteroDosKeyTyped(evt);
            }
        });
        jPanel1.add(txtEnteroDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 60, 30));

        jLabel2.setText("=");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 10, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("=");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 20, 30));

        txtNumeroTres.setEditable(false);
        jPanel1.add(txtNumeroTres, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 60, 30));

        txtDenominadorTres.setEditable(false);
        jPanel1.add(txtDenominadorTres, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 60, 30));

        txtEnteroTres.setEditable(false);
        jPanel1.add(txtEnteroTres, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 60, 30));

        cmdCalcular.setText("Calcular");
        cmdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(cmdCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));

        cmdFraccionarios.setText("Convertir A Fraccionarios");
        cmdFraccionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFraccionariosActionPerformed(evt);
            }
        });
        jPanel1.add(cmdFraccionarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        txtNumerador1.setEditable(false);
        jPanel1.add(txtNumerador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 60, 30));

        txtDemoninador.setEditable(false);
        jPanel1.add(txtDemoninador, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 60, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 80, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 60, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 340));

        setSize(new java.awt.Dimension(636, 378));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcularActionPerformed

        int Oper, Nume1, Nume2, Deno1, Deno2, Ente1, Ente2;
        clase Mixt1, Mixt2, Mixt3 = null;

        if (txtPrimerEntero.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Digite El Valor Entero", "Error", JOptionPane.ERROR_MESSAGE);
            txtPrimerEntero.requestFocusInWindow();
        } else if (txtDenominadorUno.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite El Denominador", "Error", JOptionPane.ERROR_MESSAGE);
            txtDemominadorDos.requestFocusInWindow();
        } else if (txtNumeroUno.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite El Numerador", "Error", JOptionPane.ERROR_MESSAGE);
            txtNumeroUno.requestFocusInWindow();
        } else if (txtNumeroDos.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite El Numerador", "Error", JOptionPane.ERROR_MESSAGE);
            txtEnteroDos.requestFocusInWindow();
        } else if (txtDemominadorDos.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite El Denominador", "Error", JOptionPane.ERROR_MESSAGE);
            txtDemominadorDos.requestFocusInWindow();
        } else if (txtEnteroDos.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite El Valor Entero", "Error", JOptionPane.ERROR_MESSAGE);
            txtEnteroDos.requestFocusInWindow();
        } else {
            Oper = cmbOper.getSelectedIndex();
            Nume1 = Integer.parseInt(txtNumeroUno.getText());
            Ente1 = Integer.parseInt(txtPrimerEntero.getText());
            Deno1 = Integer.parseInt(txtDenominadorUno.getText());
            Nume2 = Integer.parseInt(txtNumeroDos.getText());
            Ente2 = Integer.parseInt(txtEnteroDos.getText());
            Deno2 = Integer.parseInt(txtDemominadorDos.getText());
            try {
                Mixt1 = new clase(Nume1, Deno1, Ente1);
                Mixt2 = new clase(Nume2, Deno2, Ente2);
                switch (Oper) {
                    case 0:
                        Mixt3 = Mixt1.Suma(Mixt2);
                        break;
                    case 1:
                        Mixt3 = Mixt1.Resta(Mixt2);
                        break;
                    case 2:
                        Mixt3 = Mixt1.Multiplicacion(Mixt2);
                        break;
                    case 3:
                        Mixt3 = Mixt1.Division(Mixt2);
                        break;
                }
                txtNumeroTres.setText("" + Mixt3.getNumerador());
                txtDenominadorTres.setText("" + Mixt3.getDenominador());
                txtEnteroTres.setText("" + Mixt3.getNumero_Entero());
            } catch (DenominadorCeroException e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        cmdCalcular.setEnabled(true);
        cmdLimpiar.setEnabled(true);
        cmdFraccionarios.setEnabled(true);
    }//GEN-LAST:event_cmdCalcularActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed

        txtDenominadorUno.setText("");
        txtPrimerEntero.setText("");
        txtNumeroUno.setText("");
        txtDemominadorDos.setText("");
        txtEnteroDos.setText("");
        txtNumeroDos.setText("");
        txtDenominadorTres.setText("");
        txtEnteroTres.setText("");
        txtNumeroTres.setText("");
        txtDemoninador.setText("");
        txtNumerador1.setText("");
        txtPrimerEntero.requestFocusInWindow();

        cmdCalcular.setEnabled(true);
        cmdLimpiar.setEnabled(false);
        cmdFraccionarios.setEnabled(false);
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    private void cmdFraccionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFraccionariosActionPerformed

        int Nume, Deno, Ente, CFracc, CDeno;

        Nume = Integer.parseInt(txtNumeroTres.getText());
        Deno = Integer.parseInt(txtDenominadorTres.getText());
        Ente = Integer.parseInt(txtEnteroTres.getText());
        CFracc = Ente * Deno + Nume;
        CDeno = Deno;

        txtNumerador1.setText("" + CFracc);
        txtDemoninador.setText("" + CDeno);
        cmdLimpiar.setEnabled(true);
        cmdCalcular.setEnabled(false);
        cmdFraccionarios.setEnabled(false);
        txtPrimerEntero.requestFocusInWindow();

    }//GEN-LAST:event_cmdFraccionariosActionPerformed

    private void txtNumeroUnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroUnoKeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNumeroUnoKeyTyped

    private void txtNumeroDosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroDosKeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNumeroDosKeyTyped

    private void txtPrimerEnteroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrimerEnteroKeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtPrimerEnteroKeyTyped

    private void txtEnteroDosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEnteroDosKeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtEnteroDosKeyTyped

    private void txtDenominadorUnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDenominadorUnoKeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtDenominadorUnoKeyTyped

    private void txtDemominadorDosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDemominadorDosKeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtDemominadorDosKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbOper;
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JButton cmdFraccionarios;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtDemominadorDos;
    private javax.swing.JTextField txtDemoninador;
    private javax.swing.JTextField txtDenominadorTres;
    private javax.swing.JTextField txtDenominadorUno;
    private javax.swing.JTextField txtEnteroDos;
    private javax.swing.JTextField txtEnteroTres;
    private javax.swing.JTextField txtNumerador1;
    private javax.swing.JTextField txtNumeroDos;
    private javax.swing.JTextField txtNumeroTres;
    private javax.swing.JTextField txtNumeroUno;
    private javax.swing.JTextField txtPrimerEntero;
    // End of variables declaration//GEN-END:variables
}
